StoreProductsAspNetMvs/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StoreProductsAspNetMvs.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        
        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

StoreProductsAspNetMvs/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreProductsAspNetMvs.Data;
using StoreProductsAspNetMvs.ViewModels;
using StoreProductsAspNetMvs.Data.Interfacees;
using StoreProductsAspNetMvs.Data.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using PagedList.Core;

namespace StoreProductsAspNetMvs.Controllers
{
  //  [Authorize(Roles = "admin")]
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _hosting;
        public ProductsController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment hosting)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
            _hosting = hosting;
        }


        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            PagedList<Product> products = new PagedList<Product>(_productRepository.GetAll(), page, pageSize);


            ViewBag.Title = "Products Index";
            return View(products);
        }

        public async Task<IActionResult> Create()
        {
            ProductCreateViewModel model = new ProductCreateViewModel();
            model.Categories = await _categoryRepository.GetAllAsync();
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateViewModel model)
        {
          
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Img != null)
                {
                    string uploadFolder = Path.Combine(_hosting.WebRootPath, "ProductsImg");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Img.FileName;
                    string FilePath = Path.Combine(uploadFolder, uniqueFileName);
                    model.Img.CopyTo(new FileStream(FilePath, FileMode.Create));
                }
                Product product = new Product()
                {
                    CategoryId = model.CategoryId,
                    Code = model.Code,
                    Count = model.Count,
                    IsFavorite = model.IsFavorite,
                    Name = model.Name,
                    Price = model.Price,
                    ImgPath = uniqueFileName,
                    Discount = model.Discount,
                    ShortDesc = model.ShortDesc,
                    LongDesc = model.LongDesc
                };
                _productRepository.Create(product);
                await _productRepository.SaveAsync();
                return RedirectToAction("Index", await _productRepository.GetAllAsync());

            }
            model.Categories = await _categoryRepository.GetAllAsync();
            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var product = _productRepository.GetById(id);
            EditProductViewModel editProductViewModel = new EditProductViewModel()
            {
                Id = product.Id,
                Name = product.Name,
                Code = product.Code,
                Count = product.Count,
                IsFavorite = product.IsFavorite,
                Price = product.Price,
                LongDesc = product.LongDesc,
                ShortDesc = product.ShortDesc,
                ExistImgPath = product.ImgPath

            };
            editProductViewModel.Categories = await _categoryRepository.GetAllAsync();
            return View(editProductViewModel);
        }

        // POST: Category/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(EditProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Product product = _productRepository.GetById(model.Id);

                product.Name = model.Name;
                product.CategoryId = model.CategoryId;
                product.Code = model.Code;
                product.Count = model.Count;
                product.Discount = model.Discount;
                product.IsFavorite = model.IsFavorite;
                product.LongDesc = model.LongDesc;
                product.Price = model.Price;
                product.ShortDesc = model.ShortDesc;

                if (model.Img != null)
                {
                    if (model.ExistImgPath != null)
                    {
                        string filePath = Path.Combine(_hosting.WebRootPath, "ProductsImg", model.ExistImgPath);
                        System.IO.File.Delete(filePath);
                    }
                    product.ImgPath = ProcessUploadingFile(model);

                }

                _productRepository.Update(product);
                await _categoryRepository.SaveAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        private string ProcessUploadingFile(ProductCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.Img != null)
            {
                string uploadFolder = Path.Combine(_hosting.WebRootPath, "ProductsImg");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Img.FileName;
                string FilePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(FilePath, FileMode.Create))
                {
                    model.Img.CopyTo(fileStream);
                }

            }

            return uniqueFileName;
        }


    }
}

StoreProductsAspNetMvs/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreProductsAspNetMvs.Data.Models;
using StoreProductsAspNetMvs.ViewModels;

namespace StoreProductsAspNetMvs.Controllers
{
   // [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

StoreProductsAspNetMvs/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreProductsAspNetMvs.Data.Models;
using StoreProductsAspNetMvs.ViewModels;

namespace StoreProductsAspNetMvs.Controllers
{
   // [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.UserName  };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, UserName = user.UserName };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.UserName = model.UserName;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

StoreProductsAspNetMvs/Views/Shared/_Footer.cshtml
    <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
        <div class="w3-row-padding">
            <div class="w3-col s4">
                <h4>Contact</h4>
                <p>Questions? Go ahead.</p>
                <form action="/action_page.php" target="_blank">
                    <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
                    <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
                    <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
                    <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
                    <button type="submit" class="w3-button w3-block w3-black">Send</button>
                </form>
            </div>

            <div class="w3-col s4">
                <h4>About</h4>
                <p><a href="#">About us</a></p>
                <p><a href="#">We're hiring</a></p>
                <p><a href="#">Support</a></p>
                <p><a href="#">Find store</a></p>
                <p><a href="#">Shipment</a></p>
                <p><a href="#">Payment</a></p>
                <p><a href="#">Gift card</a></p>
                <p><a href="#">Return</a></p>
                <p><a href="#">Help</a></p>
            </div>

            <div class="w3-col s4 w3-justify">
                <h4>Store</h4>
                <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
                <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
                <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
                <h4>We accept</h4>
                <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
                <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
                <br>
                <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
                <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
                <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
                <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
                <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
                <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
            </div>
        </div>
        <div class="w3-black w3-center w3-padding-24">Template from w3schools <a href="https://gitlab.com/NikoyanGar" title="Created code Garik" target="_blank" class="w3-hover-opacity">w3.css</a></div>

    </footer>

StoreProductsAspNetMvs/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />

</head>
<body>

  
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark">

            <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" asp-action="Index" asp-controller="Products">Products </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Categories">Categories </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Roles">Roles </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Users">Users </a>
                    </li>
                </ul>

                <ul class="navbar-nav mr-auto">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item ">
                            <form asp-controller="Account" asp-action="Logout" method="post">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>

                            </form>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item ">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Register </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login </a>
                        </li>
                    }

                </ul>

            </div>
        </nav>
    </header>

    <div class="container mt-4 row">
        @RenderBody()
    </div>
  

</body>
</html>

StoreProductsAspNetMvs/Views/Shared/_LayoutSite.cshtml
@inject SignInManager<User> signInManager;

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="/css/LoginForm.css" rel="stylesheet" type="text/css" />
    <link href="/css/Style.css" rel="stylesheet" type="text/css" />
</head>

<body class="w3-content" style="max-width:1200px">

    @{await Html.RenderPartialAsync("_Sidebar");}

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

        <!-- Push down content on small screens -->
        <div class="w3-hide-large" style="margin-top:83px"></div>

        <!-- Top header -->
        <header class="w3-container w3-xlarge">
            <div class="w3-right">
                <div class="nav-item">
                    @if (signInManager.IsSignedIn(User))
                    {

                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                Logout @User.Identity.Name
                            </button>
                        </form>

                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Register" class="w3-bar-item w3-button">Register</a>
                        <a asp-controller="Account" asp-action="Login" class="w3-bar-item w3-button">Login</a>
                    }
                </div>
            </div>


        </header>

        <!-- Image header -->
        <div class="w3-display-container w3-container">
            <img src="/img/Comfort.png" alt="Jeans" style="width:100%">
            <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
                <h1 class="w3-jumbo w3-hide-small">Led Lights</h1>
                <h1 class="w3-hide-large w3-hide-medium">Led Lights</h1>
                <h1 class="w3-hide-small">Always the best prices</h1>
                <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
            </div>
        </div>



        <!-- Product grid -->
        <div class="container">
            @RenderBody()
        </div>

        <!-- Subscribe section -->
        @{await Html.RenderPartialAsync("_SUbscribe");}

        <!-- Footer -->
        @{await Html.RenderPartialAsync("_Footer");}



        <!-- End page content -->
    </div>

    <!-- Newsletter Modal -->
    <div id="newsletter" class="w3-modal">
        <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
            <div class="w3-container w3-white w3-center">
                <i onclick="document.getElementById('newsletter').style.display='none'"
                   class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
                <h2 class="w3-wide">NEWSLETTER</h2>
                <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
                <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
                <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom"
                        onclick="document.getElementById('newsletter').style.display='none'">
                    Subscribe
                </button>
            </div>
        </div>
    </div>

    <script>

        // Click on the "Jeans" link on page load to open the accordion for demo purposes
        document.getElementById("myBtn").click();


        // Open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }


    </script>

</body>
</html>

StoreProductsAspNetMvs/Views/Shared/_Login.cshtml
@model LoginViewModel;
@{
    Layout = "_LayoutSite";
}

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>
<div id="id01" class="modal">

    <form class="modal-content animate" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Model.ReturnUrl">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="imgcontainer">
            <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
            <img src="Img/img_avatar2.png" alt="Avatar" class="avatar">
        </div>
        <div class="container">
            <label asp-for="UserName"><b>Username</b></label>
            <input asp-for="UserName" placeholder="Enter Username" asp-validation-for="UserName" required>

            <label asp-for="Password"><b>Password</b></label>
            <input asp-for="Password" placeholder="Enter Password" asp-validation-for="Password" required>

            <button type="submit">Login</button>
            <label>
                <input type="checkbox" checked="checked" asp-for="RememberMe"> Remember me
            </label>
        </div>

        <div class="container" style="background-color:#f1f1f1">
            <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
            <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
    </form>
</div>

StoreProductsAspNetMvs/Views/Shared/_Sidebar.cshtml
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
    <div class="w3-container w3-display-container w3-padding-16">
        <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
        <h3 class="w3-wide"><b>LOGO</b></h3>
    </div>
    <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
        <a asp-controller="Home" asp-action="Categories" class="w3-bar-item w3-button">Our product categoeies</a>
        <a href="#" class="w3-bar-item w3-button"> discount items </a>

        <a asp-action="Productss" asp-controller="Home" asp-route-category="Tools" class="w3-bar-item w3-button">Tools</a>
        <a asp-action="Productss" asp-controller="Home" asp-route-category="LEd" class="w3-bar-item w3-button">Led lights</a>
        <a asp-action="Products" asp-controller="Home" asp-route-category="Acces" class="w3-bar-item w3-button">Accessories</a>
        <a asp-action="Products" asp-controller="Home" asp-route-category="Chan" class="w3-bar-item w3-button">Chandeliers</a>

    </div>
    <a href="#footer" class="w3-bar-item w3-button w3-padding">Contact</a>
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding" onclick="document.getElementById('newsletter').style.display='block'">Newsletter</a>
    <a href="#footer" class="w3-bar-item w3-button w3-padding">Subscribe</a>
</nav>

<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
    <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

StoreProductsAspNetMvs/Views/Shared/_Subscribe.cshtml
    <div class="w3-container w3-black w3-padding-32">
        <h1>Subscribe</h1>
        <p>To get special offers and VIP treatment:</p>
        <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
        <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
    </div>