StoreProductsAspNetMvs/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreProductsAspNetMvs.Data;
using StoreProductsAspNetMvs.ViewModels;
using StoreProductsAspNetMvs.Data.Interfacees;
using StoreProductsAspNetMvs.Data.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using PagedList.Core;

namespace StoreProductsAspNetMvs.Controllers
{
  //  [Authorize(Roles = "admin")]
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _hosting;
        public ProductsController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment hosting)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
            _hosting = hosting;
        }


        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            PagedList<Product> products = new PagedList<Product>(_productRepository.GetAll(), page, pageSize);


            ViewBag.Title = "Products Index";
            return View(products);
        }

        public async Task<IActionResult> Create()
        {
            ProductCreateViewModel model = new ProductCreateViewModel();
            model.Categories = await _categoryRepository.GetAllAsync();
            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateViewModel model)
        {
          
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Img != null)
                {
                    string uploadFolder = Path.Combine(_hosting.WebRootPath, "ProductsImg");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Img.FileName;
                    string FilePath = Path.Combine(uploadFolder, uniqueFileName);
                    model.Img.CopyTo(new FileStream(FilePath, FileMode.Create));
                }
                Product product = new Product()
                {
                    CategoryId = model.CategoryId,
                    Code = model.Code,
                    Count = model.Count,
                    IsFavorite = model.IsFavorite,
                    Name = model.Name,
                    Price = model.Price,
                    ImgPath = uniqueFileName,
                    Discount = model.Discount,
                    ShortDesc = model.ShortDesc,
                    LongDesc = model.LongDesc
                };
                _productRepository.Create(product);
                await _productRepository.SaveAsync();
                return RedirectToAction("Index", await _productRepository.GetAllAsync());

            }
            model.Categories = await _categoryRepository.GetAllAsync();
            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var product = _productRepository.GetById(id);
            EditProductViewModel editProductViewModel = new EditProductViewModel()
            {
                Id = product.Id,
                Name = product.Name,
                Code = product.Code,
                Count = product.Count,
                IsFavorite = product.IsFavorite,
                Price = product.Price,
                LongDesc = product.LongDesc,
                ShortDesc = product.ShortDesc,
                ExistImgPath = product.ImgPath

            };
            editProductViewModel.Categories = await _categoryRepository.GetAllAsync();
            return View(editProductViewModel);
        }

        // POST: Category/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(EditProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Product product = _productRepository.GetById(model.Id);

                product.Name = model.Name;
                product.CategoryId = model.CategoryId;
                product.Code = model.Code;
                product.Count = model.Count;
                product.Discount = model.Discount;
                product.IsFavorite = model.IsFavorite;
                product.LongDesc = model.LongDesc;
                product.Price = model.Price;
                product.ShortDesc = model.ShortDesc;

                if (model.Img != null)
                {
                    if (model.ExistImgPath != null)
                    {
                        string filePath = Path.Combine(_hosting.WebRootPath, "ProductsImg", model.ExistImgPath);
                        System.IO.File.Delete(filePath);
                    }
                    product.ImgPath = ProcessUploadingFile(model);

                }

                _productRepository.Update(product);
                await _categoryRepository.SaveAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        private string ProcessUploadingFile(ProductCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.Img != null)
            {
                string uploadFolder = Path.Combine(_hosting.WebRootPath, "ProductsImg");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Img.FileName;
                string FilePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(FilePath, FileMode.Create))
                {
                    model.Img.CopyTo(fileStream);
                }

            }

            return uniqueFileName;
        }


    }
}

StoreProductsAspNetMvs/Controllers/categoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using StoreProductsAspNetMvs.Data.Interfacees;
using StoreProductsAspNetMvs.Data.Models;
using StoreProductsAspNetMvs.ViewModels;

namespace StoreProductsAspNetMvs.Controllers
{
  //  [Authorize(Roles = "admin")]
    public class CategoriesController : Controller
    {
        public CategoriesController(ICategoryRepository categoryRepository, IWebHostEnvironment hosting)
        {
            _categoryRepository = categoryRepository;
            _hosting = hosting;
        }
        private readonly ICategoryRepository _categoryRepository;

        private readonly IWebHostEnvironment _hosting;

        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            PagedList<Category> categories = new PagedList<Category>(_categoryRepository.GetAll(), page, pageSize);


            ViewBag.Title = "Products Index";
            return View(categories);
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        public async Task<ActionResult> Create(CategoryCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadingFile(model);
              
                Category category = new Category()
                {
                    Name = model.Name,
                    ImgPath = uniqueFileName,
                };
                _categoryRepository.Create(category);
                await _categoryRepository.SaveAsync();
                return View();
            }
            return RedirectToAction("Index", await _categoryRepository.GetAllAsync());
        }
        // GET: Category/Edit/5
        public ActionResult Edit(int id)
        {
          var category=  _categoryRepository.GetById(id);
            EditCategoryViewModel editCategoryViewModel = new EditCategoryViewModel()
            {
                Id = category.Id,
                Name = category.Name,
                ExistImgPath = category.ImgPath

            };
            return View(editCategoryViewModel);
        }

        // POST: Category/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(EditCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                Category category = _categoryRepository.GetById(model.Id);
                category.Name = model.Name;
                if (model.Img!=null)
                {
                    if (model.ExistImgPath!=null)
                    {
                      string filePath=  Path.Combine(_hosting.WebRootPath, "CategoryImg", model.ExistImgPath);
                        System.IO.File.Delete(filePath);///????????
                    }
                   category.ImgPath= ProcessUploadingFile(model);

                }
             
                _categoryRepository.Update(category);
                await _categoryRepository.SaveAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

       
        // GET: Category/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Category/Delete/5
        [HttpPost]
        public async Task< ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                _categoryRepository.Delete(id);
                await _categoryRepository.SaveAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private string ProcessUploadingFile(CategoryCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.Img != null)
            {
                string uploadFolder = Path.Combine(_hosting.WebRootPath, "CategoryImg");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Img.FileName;
                string FilePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream= new FileStream(FilePath, FileMode.Create))
                {
                    model.Img.CopyTo(fileStream);
                }
              
            }

            return uniqueFileName;
        }

    }
}

StoreProductsAspNetMvs/Views/Products/Create.cshtml
@model ProductCreateViewModel



    <form enctype="multipart/form-data" class="form-group" method="post" asp-controller="Products" asp-action="Create">
        <div asp-validation-summary="ModelOnly"></div>
        <h1 class="h3 mb-3 font-weight-normal">Create New Product</h1>
        

        <label asp-for="Name" class="sr-only">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name" asp-validation-for="Name">

        <label asp-for="ShortDesc" class="sr-only">ShortDesc</label>
        <input asp-for="ShortDesc" class="form-control" placeholder="ShortDesc" asp-validation-for="ShortDesc">

        <label asp-for="LongDesc" class="sr-only">LongDesc</label>
        <input asp-for="LongDesc" class="form-control" placeholder="LongDesc" asp-validation-for="LongDesc">

        <label asp-for="Code" class="sr-only">Code</label>
        <input asp-for="Code" class="form-control" placeholder="Code" asp-validation-for="Code">

        <label asp-for="Price" class="sr-only">Price</label>
        <input asp-for="Price" type="number" class="form-control" placeholder="Price" asp-validation-for="Price">

        <label asp-for="Discount" class="sr-only">Discount-%</label>
        <input asp-for="Discount" type="number" class="form-control" placeholder="Discount" asp-validation-for="Discount">

        <label asp-for="Count" class="sr-only">Count</label>
        <input asp-for="Count" type="number" class="form-control" placeholder="Count" asp-validation-for="Count">

        <label class="sr-only">Category</label>
        <select asp-for="CategoryId" class="custom-select">
            @foreach (Category item in Model.Categories)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <div class="custom-file">
            <input asp-for="Img" type="file" class="form-control custom-file-input">
            <label asp-for="Img" class="custom-file-label">Choose file</label>
        </div>

        <div class="checkbox mb-3">
            <label asp-for="IsFavorite" class="custom-checkbox">
                <input type="checkbox" asp-for="IsFavorite"> Is in Favorite?
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
        <script>
            $(document).ready(function () {
                $(".custom-file-input").on("change", function () {
                    var filename = $(this).val().split("\\").pop();
                    $(this).next(".custom-file-label").html(filename);
                });
            });
        </script>
    </form>

StoreProductsAspNetMvs/Views/Products/Details.cshtml
@model Product;

<div class="col-2 row-cols-2">
    <div class="card">
        <img src="/ProductsImg/@Model.ImgPath" alt="Product Image" style="width:100%">
        <h1>@Model.Name</h1>
        <p class="price">@Model.Price.ToString("c")</p>
        <p><i>@Model.ShortDesc</i></p>
        <p>@Model.LongDesc</p>
        <p>IsInFavorite:<b>@Model.IsFavorite</b></p>
        <p>Discount %: @Model.Discount </p>
        <p>Count: @Model.Count</p>
        <p></p>
    </div>
</div>

StoreProductsAspNetMvs/Views/Products/Edit.cshtml
@model EditProductViewModel

<form enctype="multipart/form-data" class="form-group" method="post" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ExistImgPath" />

    <label asp-for="Name" class="sr-only">
    </label><input asp-for="Name" class="form-control" placeholder="Name" asp-validation-for="Name" />

    <label asp-for="Code" class="sr-only"></label>
    <input asp-for="Code" class="form-control" placeholder="Code" asp-validation-for="Code" />

    <label asp-for="Price" class="sr-only"></label>
    <input asp-for="Price" class="form-control" placeholder="Price" asp-validation-for="Price" />

    <label asp-for="Count" class="sr-only"></label>
    <input asp-for="Count" class="form-control" placeholder="Count" asp-validation-for="Count" />

    <label asp-for="IsFavorite" class="custom-checkbox"></label>
    <input asp-for="IsFavorite" class="form-control" asp-validation-for="IsFavorite" />

    <label asp-for="ShortDesc" class="sr-only"></label>
    <input asp-for="ShortDesc" class="form-control" placeholder="ShortDesc" asp-validation-for="ShortDesc" />

    <label asp-for="LongDesc" class="sr-only"></label>
    <input asp-for="LongDesc" class="form-control" placeholder="LongDesc" asp-validation-for="LongDesc" />

    <label asp-for="Discount" class="sr-only">Discount-%</label>
    <input asp-for="Discount" type="number" class="form-control" placeholder="Discount" asp-validation-for="Discount">

    <p>
        Category:
        <label class="sr-only">Category</label>
        <select asp-for="CategoryId" class="custom-select">
            @foreach (Category item in Model.Categories)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
    </p>

    <div class="custom-file">
        <input asp-for="Img" type="file" class="form-control custom-file-input">
        <label asp-for="Img" class="custom-file-label">Click here to change img</label>
    </div>

    <div class="form-group row col-sm-4 offset-4">
        <img src="/ProductsImg/@Model.ExistImgPath" class="img-thumbnail" asp-append-version="true" />
    </div>
    <div class="form-group">
        <input type="submit" value="Update" class="btn btn-primary" />
        <a asp-controller="Categories" asp-action="Index">Cancel</a>
    </div>
</form>



<div>
    <a asp-action="Index">Back to List</a>
</div>
<script>
    $(document).ready(function () {
        $(".custom-file-input").on("change", function () {
            var filename = $(this).val().split("\\").pop();
            $(this).next(".custom-file-label").html(filename);
        });
    });
</script>

StoreProductsAspNetMvs/Views/Products/Index.cshtml
@model PagedList.Core.IPagedList<Product>;

<a class="btn btn-warning" asp-action="Create">Create new Product</a>

<div class="row ">
    @{
        foreach (Product product in Model)
        {
            <div class="col-lg-3">
                <div class=" row-cols-4">
                    <img class="img-thumbnail" src="/ProductsImg/@product.ImgPath" alt="@product.Name" />
                </div>
                <div class="row-cols-4">
                    <a class="btn btn-dark" asp-action="Edit" asp-route-id="@product.Id">Edit</a>
                    <a class="btn btn-warning" asp-action="Remove" asp-route-id="@product.Id">Delete</a>
                    <a class="btn btn-info" asp-action="Remove" asp-route-id="@product.Id">Details</a>
                </div>
            </div>
        }
    }

</div>
<div class="row pagination">

    <pager list="@Model" asp-controller="Products" asp-action="Index" />
</div>